# Generated by Django 4.2.4 on 2023-12-02 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('longitud_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField()),
                ('entrada_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ponderado_compra', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_negocio', models.DateField()),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cedula_nit', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('entrada_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salida_material_1_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salida_material_2_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salida_material_3_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
