# Generated by Django 4.2.4 on 2023-12-05 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('cedula_nit', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('factura', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centro_costos', models.CharField(max_length=255)),
                ('medio_pago', models.CharField(max_length=255)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rtefte', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('neto', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
