# Generated by Django 4.2.4 on 2023-12-11 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_negocio', models.DateField()),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cedula_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField()),
                ('fv_rc', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField()),
                ('centro_costos', models.CharField(max_length=255)),
                ('medio_pago', models.CharField(max_length=50)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rtefte', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalidaMateriaPrima',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('salida_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salida_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pondera_vta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ponderado_salida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprobante_ingreso', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
