# Generated by Django 4.2.4 on 2023-12-02 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostosDeProduccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_negocio', models.DateField()),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cedula_nit', models.CharField(max_length=20)),
                ('contacto', models.BigIntegerField()),
                ('descripcion', models.TextField()),
                ('fv_rc', models.CharField(blank=True, max_length=15, null=True)),
                ('cantidad', models.IntegerField()),
                ('centro_de_costos', models.CharField(max_length=255)),
                ('medio_pago', models.CharField(max_length=255)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rtefte', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('neto', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GastosComprasConstruccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_negocio', models.DateField()),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('cedula_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('fv_rc', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('centro_de_costos', models.CharField(max_length=255)),
                ('medio_pago', models.CharField(max_length=255)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rtefte', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('neto', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioMaquinaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_adquisicion', models.DateField()),
                ('item', models.IntegerField()),
                ('equipo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('centro_costos', models.CharField(max_length=255)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo_peritaje', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo_entrada', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
