# Generated by Django 4.2.4 on 2023-12-02 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadroEstadistico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('ventas_mes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ponderado_materia_prima', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costos_produccion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gastos_construccion_taller_callao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ventas_ano_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ventas_ano_actual', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VentaMensual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('mes', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformeComportamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('costos_produccion', models.ManyToManyField(related_name='informes_comportamiento', to='produccion.costosdeproduccion')),
                ('entradas', models.ManyToManyField(related_name='informes_comportamiento', to='ingresos.entrada')),
                ('gastos_construccion', models.ManyToManyField(related_name='informes_comportamiento', to='produccion.gastoscomprasconstruccion')),
                ('ingresos', models.ManyToManyField(related_name='informes_comportamiento', to='ingresos.ingreso')),
                ('inventario_maquinaria', models.ManyToManyField(related_name='informes_comportamiento', to='produccion.inventariomaquinaria')),
                ('ventas', models.ManyToManyField(related_name='informes_comportamiento', to='informes.ventamensual')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
