# Generated by Django 4.2.4 on 2023-12-11 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteraPagareYAnticipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_negocio', models.DateField(auto_now_add=True)),
                ('nombre_completo_razon_social', models.CharField(max_length=255)),
                ('cedula_nit', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('valor_pagare', models.DecimalField(decimal_places=2, max_digits=15)),
                ('abono_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pagos_ano', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('descuentos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ComparativoIngresosCompras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ingresos_efectivo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ingreso_caja_sky', models.DecimalField(decimal_places=2, max_digits=15)),
                ('compras', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gastos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gastos_compras_callao', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformeDiarioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('fv', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('venta_directa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('venta_credito', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('acumulado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InformeDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('numero_informe', models.IntegerField()),
                ('fecha_informe', models.DateField()),
                ('items', models.ManyToManyField(related_name='informes', to='informes.informediarioitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
