from apps.invetarios.models.inventario_stock import InventarioStock
from apps.invetarios.models.costo_producto import CostoProducto
from apps.invetarios.models.otro_inventario_stock import OtrosInventarioStockEntra
from apps.invetarios.models.pedido_materia_prima import PedidoMateriaPrima
from apps.invetarios.models.precio_por_año import PrecioProveedorPorAno